name: semantic_mapper
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=6_kmp_llvm
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=2.137=mkl
  - blas-devel=3.9.0=37_hcf00494_mkl
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - ceres-solver=2.2.0=cpuhace6338_8
  - colmap=3.10=gpuh6abe98f_103
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - eigen=3.4.0=h171cf75_1
  - filelock=3.20.0=pyhd8ed1ab_0
  - flann=1.9.2=h776a335_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h49ef1fa_24
  - freetype=2.14.1=ha770c72_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.86.2=h5192d8d_1
  - glib-tools=2.86.2=hf516916_1
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_2
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - imath=3.2.2=hde8ca8f_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jasper=4.2.8=he3c4edf_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=37_h5875eb1_mkl
  - libboost=1.86.0=hed09d94_4
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=37_hfef963f_mkl
  - libclang-cpp21.1=21.1.6=default_h99862b1_0
  - libclang13=21.1.6=default_h746c552_0
  - libcublas=12.4.5.8=he02047a_2
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.5.147=he02047a_2
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h6548e54_1
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=37_h5e43f62_mkl
  - liblapacke=3.9.0=37_hdba1596_mkl
  - libllvm21=21.1.6=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libpq=18.1=h5c52fec_1
  - libprotobuf=6.31.1=h49aed37_2
  - libraw=0.21.4=h9969a89_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.7.1=cpu_mkl_hf38bc2d_103
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.3=py311h3778330_0
  - metis=5.1.0=hd0bcaf9_1007
  - mkl=2024.2.2=ha770c72_17
  - mkl-devel=2024.2.2=ha770c72_17
  - mkl-include=2024.2.2=ha770c72_17
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6=pyhcf101f3_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=2.3.5=py311h2e04523_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openexr=3.4.4=he10986b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.25.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py311hdf67eae_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py311h07c5bb8_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=h9a6aba3_3
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycolmap=3.10=cuda120py311h34d7ff8_2
  - python=3.11.14=hd63d673_2_cpython
  - python_abi=3.11=8_cp311
  - pytorch=2.7.1=cpu_mkl_py311_h7bde0a3_103
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py311h3778330_0
  - qt-main=5.15.15=h3c3fd16_6
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sleef=3.9.0=ha0421bc_0
  - suitesparse=7.8.2=hb42a789_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.13=noxft_ha0e22de_103
  - torchtriton=3.1.0=py311
  - torchvision=0.24.0=cpu_py311_h9bcb066_0
  - torchvision-extra-decoders=0.0.2=py311ha44aed6_3
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - vlfeat=0.9.21=hd590300_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
