name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.2=py313hfc0e8ea_100
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - archspec=0.2.5=pyhd8ed1ab_0
  - boltons=25.0.0=py313h06a4308_0
  - brotlicffi=1.1.0.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.7.0=py313h78bf25f_0
  - conda-anaconda-telemetry=0.2.0=py313h06a4308_1
  - conda-anaconda-tos=0.2.1=py313h06a4308_1
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=py313h06a4308_0
  - cpp-expected=1.1.0=hff21bea_1
  - cryptography=45.0.6=py313hafb0bba_0
  - distro=1.9.0=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - fmt=11.2.0=h07f6e7f_0
  - frozendict=2.4.6=py313h536fd9c_0
  - idna=3.10=pyhd8ed1ab_1
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=3.0.0=py313h78bf25f_1
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.44=h1423503_1
  - libarchive=3.8.1=gpl_h98cc613_100
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=2.3.1=hae34dd5_1
  - libmambapy=2.3.1=py313h78de39b_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxml2=2.13.8=h2cb61b6_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.3.1=py313h78bf25f_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.11.3=he02047a_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=py313h06a4308_0
  - pydantic-core=2.33.2=py313hc6f7160_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hec9711d_102_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.4=py313h06a4308_0
  - rich=14.1.0=pyhe01879c_0
  - ruamel.yaml=0.18.14=py313h536fd9c_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=3.13.0=h84d6215_0
  - sqlite=3.50.4=hbc0de68_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - filelock==3.19.1
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - git-filter-repo==2.47.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - open-clip-torch==3.2.0
      - pillow==11.3.0
      - pyyaml==6.0.3
      - regex==2025.9.18
      - safetensors==0.6.2
      - sympy==1.14.0
      - timm==1.0.20
      - torch==2.8.0
      - torchvision==0.23.0
      - triton==3.4.0
      - wcwidth==0.2.14
